modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Aeltumn/Chisels-and-Bits2/issues"

[[mods]]
modId="chiselsandbits2"
version="${file.jarVersion}"
displayName="Chisels & Bits 2"
updateJSONURL="https://github.com/Aeltumn/Chisels-and-Bits-2/raw/master/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/chisels-bits-2"
logoFile="chiselsandbits2.png"
credits="Original mod created by AlgorithmX2"
authors="Aeltumn, AlgorithmX2"
description="The successor to the original Chisels and Bits mod. A mod about sculpting, decorating and aesthetics."
[[dependencies.chiselsandbits2]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.22,)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.chiselsandbits2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"

# Soft dependency on JEI versions 6.0.2.11 or newer for mc 1.15
[[dependencies.chiselsandbits2]]
    modId="jei"
    mandatory=false
    versionRange="[6.0.2.11,)"
    ordering="BEFORE"
    side="BOTH"
